
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Navbar } from "@/app/components/navbar/Navbar";
import "./styleFondoOro.css"

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <div
                    // id='fondo-oro-verde' 
                    className="flex flex-col items-center justify-center min-h-[calc(100vh)] font-[family-name:var(--font-geist-sans)] px-2 py-2 bg-[#007c7c]">
                    <Navbar />
                    {children}
                </div>
            </body>
        </html>
    );
}

